feeds:
- id: microsoft_news
  label: "Microsoft newsroom (press releases)"
  url: "https://news.microsoft.com/feed/"
  tags: [press, investor-relations]

- id: apple_newsroom
  label: "Apple Newsroom (press releases)"
  url: "https://www.apple.com/newsroom/rss-feed.rss"
  tags: [press, newsroom]